name: Roman A. notes
description: Some words about software development and around
meta_description: "Blog about development, software, business, work"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://qpbp.name'
google_analytics: 'UA-80542312-1'
gems: [jekyll-paginate, jekyll-seo-tag]

# Details for the RSS feed generator
url:            'qpbp.name'
author:         'Roman'
